### ISSUE TITLE
Extreme value distributions

### ISSUE THREAD

**Issue by shadrackkibet** [aursiber/fitdistrplus#6]
Hi,

Does this package work with extreme values distributions i.e `gev, generalised pareto` and `gumbel` distributions?

An example below using `texmex` package seems to crash out R as shown in the screenshot below.

```
library(texmex)
fitdistrplus::fitdist(data=1:1000, method="mle", distr="gev", start = list(mu=0, sigma=1, xi=.5))
```
![image](https://user-images.githubusercontent.com/26301973/107152452-01f93280-6979-11eb-9e26-89ec6c8917ab.png)

What could be wrong with this? any other alternatives?

**Comment by dutangc** [comment]
Dear user, 
This has nothing to do with fitdistrplus. Preliminary tests in fitdist() check that dfun() function returns an empty vector when provided an empty input.
Please contact Harry Southworth so that texmex, https://cran.r-project.org/web/packages/texmex/index.html, does not crash on the following code : 

library(texmex)
dgev(numeric(0), "mu"=0, "sigma"=1, "xi"=1)
